png(file='plot1.png', width=480, height=480)
data <- read.table("household_power_consumption.txt", header=TRUE, sep=';')
data$Date <- as.Date(as.character(data$Date), "%d/%m/%Y")
data_plot1 <- subset(data, Date >= as.Date("2007-02-01") & Date <= as.Date("2007-02-02"))
data_plot1$Global_active_power <- as.numeric(as.character(data_plot1$Global_active_power))
hist(data_plot1$Global_active_power, main='Global Active Power', col='red', xlab='Global Active Power (kilowatts)')
dev.off()
