png(file='plot3.png', width=480, height=480)
data <- read.table("household_power_consumption.txt", header=TRUE, sep=';')
data$Date <- as.Date(as.character(data$Date), "%d/%m/%Y")
data_plot3 <- subset(data, Date >= as.Date("2007-02-01") & Date <= as.Date("2007-02-02"))
data_plot3$Time <- format(as.POSIXct(paste(data_plot3$Date, data_plot3$Time)), "%Y-%m-%d %H:%M:%S")
data_plot3$Time <- strptime(data_plot3$Time, format="%Y-%m-%d %H:%M:%S")
data_plot3$Sub_metering_1 <- as.numeric(as.character(data_plot3$Sub_metering_1))
data_plot3$Sub_metering_2 <- as.numeric(as.character(data_plot3$Sub_metering_2))
data_plot3$Sub_metering_3 <- as.numeric(as.character(data_plot3$Sub_metering_3))
with(data_plot3, plot(Time, Sub_metering_1, xlab='', ylab='Energy sub metering', type='l'))
with(data_plot3, lines(Time, Sub_metering_2, col='red'))
with(data_plot3, lines(Time, Sub_metering_3, col='blue'))
legend('topright', pch=c(NA, NA, NA), lwd=1, col=c('black', 'red', 'blue'), legend=c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'))
dev.off()
